# Generated by Django 3.1.3 on 2020-11-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_auto_20201114_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelompok',
            old_name='keeterangan',
            new_name='keterangan',
        ),
    ]
