# Generated by Django 3.1.3 on 2020-11-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0005_auto_20201114_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='penertbit',
            new_name='penerbit',
        ),
    ]
